steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/My First Projecte/My First Project:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/My First Project/My First Project:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'My First Project', '--image=gcr.io/cloud-run-cd-example/My First Project:$SHORT_SHA', '--region=us-central1']
