steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/innate-sunrise-339711/cicd:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/innate-sunrise-339711/cicd:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cicd', '--image=gcr.io/innate-sunrise-339711/cicd:$SHORT_SHA', '--region=us-central1']

